### PR TITLE
Added documentation for CanUnlockCodeLock and CanAssignBedToUser

### PR DESCRIPTION
**Pull request by cjmagee**

### CODE REVIEW

**Comment by lukespragg** [comment]
We'd likely go with CanAssignBed for the first, and I'm not sure why CanUnlockCodeLock is necessary when you already have CanUseLock.

**Comment by cjmagee** [comment]
Mmmkay.

CanAssignBed included the player's ID in case it is dependent on the player.

CanUseLock does not prevent submission of the code, only using the door *after* you have already authorized.

**Comment by lukespragg** [comment]
We'd extend CanUseLock to that location then, not add another hook.

**Comment by cjmagee** [comment]
Updated to share CanUseLock

**Comment by Mughisi** [comment]
This was included in commit https://github.com/OxideMod/Docs/commit/561f7eaadd000ea26f7f1f6e474d0fd1b3f8d2b6

**Pull request closed without merging**
