### PR TITLE
More JS, and more in Getting Started

### PR DESCRIPTION
**Pull request by tprobinson**
Since I'm particularly interested in using the Javascript interface, I figured I should contribute my findings, and flesh out some of the general documentation based on my forum research while I was at it.

### CODE REVIEW

**Comment by lukespragg** [comment]
Some of this is okay, but a lot of it won't work as the Docs are in the process of being updated to Oxide's Covalence (universal) API. A specific example would be the change you made from player.Reply to player.ChatMessage in a page that is used by every game, where player.Reply is the universal function from Oxide and player.ChatMessage is specific to Rust.

**Comment by tprobinson** [comment]
Ah, I was afraid of that, I did notice that I was breaking conventions like that. Unfortunately, I wasn't able to get player.Reply to work, it did not exist on the player object I was being given in the chat command handler function, which is why I sought a workaround.

I don't mind if the parts that aren't universal are removed.

**Comment by tprobinson** [comment]
Sorry for the delay! I synced this up with your changes and removed the `rust.SendChatMessage`. I'm not sure, unfortunately, if `console.ReplyWith` is a Rust-specific thing or not? If it is, let me know and I'll remove it.

**Comment by lukespragg** [comment]
Sorry for the delay with this, but it ended up being that support for JS was dropped due to lack of maintainers for the extension itself and plans going forward.

**Pull request closed without merging**
