### PR TITLE
added CanBradlyApcTarget

### PR DESCRIPTION
**Pull request by PurePlugin**

### CODE REVIEW

**Comment by lukespragg** [comment]
These are actually bool and object hooks, not void. The Gemfile.lock doesn't need to be updated either.

**Comment by PurePlugin** [comment]
Alright i'm adding a gitignore & I was just sticking to what all the other examples were doing :)

**Comment by lukespragg** [comment]
The .gitignore is already updated and Gemfile.lock removed.

**Comment by lukespragg** [comment]
Tell ya what, to save you some time I'll add them locally. I have to sift through the other 2 PRs that were forgotten about too. :P

**Comment by PurePlugin** [comment]
hmm, still a newb w/ git sorry! trying to figure out what I did wrong

**Comment by PurePlugin** [comment]
so for things like CanBradleyApcTarget should I use 'bool?' instead of void?

**Comment by lukespragg** [comment]
Take a look here: https://github.com/OxideMod/Docs/blob/master/source/includes/rust/hooks_entity.md

**Pull request closed without merging**
